### ISSUE TITLE
Custom Key to "send text to openai" doesn't seem to work

### ISSUE THREAD

**Issue by lazywei** [yohasebe/openai-chat-api-workflow#22]
This is my current setup
![image](https://github.com/yohasebe/openai-chat-api-workflow/assets/2840571/c5efcb3c-0392-4223-866c-13f55dcc5f01)

But when I select some text and press the hotkey, what I got is like below
![image](https://github.com/yohasebe/openai-chat-api-workflow/assets/2840571/cbf154cd-8cb9-4aa1-ac29-71d515cb6305)

And then whatever I press (Enter, CMD+Enter, Shift+Enter etc.) there is no response. Alfred just show the query mode list filter.

But if I change the output route to be like this (the red arrow), it works
![image](https://github.com/yohasebe/openai-chat-api-workflow/assets/2840571/2e7a8b3e-b1fd-4f43-a335-5514d3a359da)

Not sure if I miss anything

**Comment by yohasebe** [comment]
Thanks for your report! I have confirmed the issue and the next release will fix it.

**Comment by lazywei** [comment]
confirmed this is fixed for me
