### ISSUE TITLE
Latest version close safari automatically after GPT's response finished

### ISSUE THREAD

**Issue by lazywei** [yohasebe/openai-chat-api-workflow#25]
It seems on the latest version 2.8.3 the browser (safari) will close itself after the GPT finishes streaming.

**Comment by yohasebe** [comment]
Hi, thank you for your report. I confirmed that `2.8.3` had issues with Safari. Please try `2.8.4`, which offers improved support for Safari.

**Comment by lazywei** [comment]
Confirmed it's now working, thank you!
